import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopNav from "./_components/TopNav";
import desktopBG from "@/assets/desktopBG.png"


const teachers = localFont({
  src: "./fonts/Teachers-VariableFont_wght.ttf",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const divStyle: React.CSSProperties = {
  //   backgroundImage: `url(${topShape.src})`,
  //   backgroundSize: '',
  //   backgroundRepeat: "no-repeat",
  //   backgroundPosition: 'center',
  // };
  const BGStyle: React.CSSProperties = {
    backgroundImage: `url(${desktopBG.src})`,
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: '30% center',
    backgroundAttachment: "fixed"
  };
  return (
    <html lang="en">
      <body
      style={BGStyle}
        className={`${teachers.className} antialiased bg-orange-50 lg:bg-bottom`}
      >
        <TopNav></TopNav>
      


      {/* <nav className="h-[10vh] p-3 bg-accent lg:hidden block" style={divStyle}>
      </nav> */}
        {children}
      </body>
    </html>
  );
}
