import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import topShape from "@/assets/top_shape.png"
import TopNav from "./_components/TopNav";


const teachers = localFont({
  src: "./fonts/Teachers-VariableFont_wght.ttf",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const divStyle: React.CSSProperties = {
    backgroundImage: `url(${topShape.src})`,
    backgroundSize: '',
    backgroundRepeat: "no-repeat",
    backgroundPosition: 'center',
  };
  return (
    <html lang="en">
      <body
        className={`${teachers.className} antialiased bg-orange-50`}
      >
        <TopNav></TopNav>
      


      <nav className="h-[10vh] p-3 bg-accent lg:hidden block" style={divStyle}>
      </nav>
        {children}
      </body>
    </html>
  );
}
